# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Validate-Email
version:      0.04
version_from: Email.pm
installdirs:  site
requires:
    Data::Validate::Domain:        0.04
    Email::Address:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
